name: Sync Requirements

on:
  push:
    branches:
      - main

jobs:
  sync-requirements:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: pip install poetry poetry-plugin-export

      - name: Export requirements.txt
        run: poetry export -f requirements.txt --output requirements.txt --without-hashes

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update requirements.txt from pyproject.toml [auto-sync]
          file_pattern: requirements.txt
